[package]
name = "rahmen"
version = "0.1.0"
authors = ["Moritz Hoffmann <antiguru@gmail.com>"]
edition = "2018"

[features]

[[bin]]
name = "rahmen"

[profile.release]
debug = true

[dependencies]
clap = "3.0.0-beta.2"
glob = "0.3.0"
linuxfb = "0.2.0"
memmap = "0.7.0"
mozjpeg = "0.8.21"
framebuffer = "0.2.2"
minifb = { version = "0.19.1", optional = true}

[dependencies.image]
version  = "0.23.12"
default-features = false
features = ["gif", "jpeg", "ico", "png", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt", "dds", "farbfeld"]
