[package]
name = "rahmen"
version = "0.1.0"
authors = ["Moritz Hoffmann <antiguru@gmail.com>"]
edition = "2018"

[features]
default = ["fltk"]

[[bin]]
name = "rahmen"

[profile.release]
debug = true

[dependencies]
clap = {version = "3.0.0-beta.2", default-features = false, features = ["color", "std"] }
ctrlc = "3.1.7"
fltk = {version = "0.12.2", optional = true, features = ["fltk-shared"]}
font-kit = "0.10.0"
framebuffer = "0.2.2"
glob = "0.3.0"
kamadak-exif = "0.5.2"
lazy_static = "1.4.0"
memmap = "0.7.0"
mozjpeg = "0.8.21"
pathfinder_geometry = "0.5.1"
reverse_geocoder = "2.0.0"
timely = {git = "https://github.com/TimelyDataflow/timely-dataflow"}

[dependencies.image]
version  = "0.23.12"
default-features = false
# Disable jpeg_rayon
features = ["jpeg"]
