[package]
name = "rahmen"
version = "0.1.0"
authors = ["Moritz Hoffmann <antiguru@gmail.com>"]
edition = "2018"

[[bin]]
name = "rahmen"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
glob = "0.3.0"
image = "0.23.12"
linuxfb = "0.2.0"
memmap = "0.7.0"
minifb = "0.19.1"