[package]
name = "rahmen"
version = "0.1.0"
authors = ["Moritz Hoffmann <antiguru@gmail.com>"]
edition = "2018"

[features]
default = ["fltk"]

[[bin]]
name = "rahmen"

[profile.release]
debug = true

[dependencies]
clap = "3.0.0-beta.2"
ctrlc = "3.1.7"
fltk = {version = "0.12.2", optional = true, features = ["fltk-shared"]}
glob = "0.3.0"
kamadak-exif = "0.5.2"
memmap = "0.7.0"
mozjpeg = "0.8.21"
framebuffer = "0.2.2"
timely = {git = "https://github.com/TimelyDataflow/timely-dataflow"}

[dependencies.image]
version  = "0.23.12"
default-features = false
# Disable jpeg_rayon
features = ["gif", "jpeg", "ico", "png", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt", "dds", "farbfeld"]
