[package]
name = "rahmen"
version = "0.1.1"
authors = ["Moritz Hoffmann <antiguru@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Rahmen is a lightweight image presenter"
readme = "README.md"

[features]
default = []

[[bin]]
name = "rahmen"

[profile.release]
debug = true

[dependencies]
clap = { version = "3.0.0-beta.2", default-features = false, features = ["color", "std"] }
config = "0.10.1"
convert_case = "0.4.0"
ctrlc = "3.1.7"
fltk = { version = "0.12.2", optional = true, features = ["fltk-shared"] }
font-kit = "0.10.0"
framebuffer = "0.2.2"
glob = "0.3.0"
itertools = "0.10.0"
memmap = "0.7.0"
mozjpeg = "0.8.21"
pathfinder_geometry = "0.5.1"
rexiv2 = "0.9.1"
regex = "1"
serde = "1.0.119"
serde_derive = "1.0.119"
timely = { git = "https://github.com/TimelyDataflow/timely-dataflow" }

[dependencies.image]
version = "0.23.12"
default-features = false
# Disable jpeg_rayon
features = ["jpeg"]
