# Configuration for Rahmen

# these will be overridden if also given on the command line
# Font size of the status line
font_size = 32
# Delay between transitions
delay = 90

# Parameters to tune the information line below the image.
# The following are probably only useful when post-processing using the python snippet
# or the line_replace regex(es).

# What to insert between the metadata, default: insert ", ".
    # separator = "|"

# when there's python code, these will be used only for the input (and should be set false, see below)
    # Should we show duplicate strings only once (default: true)?
    uniquify = false
    #Should we hide empty results (default: true)?
    hide_empty = false

py_postprocess =  "postprocess"
py_path = ["."]

# Regular expression(s) to apply to the whole line, after all the individual metadata has been processed
# and joined using the separator.
line_replacements = [
#    {regex = '(?P<text>^.*), (?P<subloc>.*), (?P<loc>.*), (?P<province>Mark), (?P<rest>.*$)', replace = '$text, $subloc ($province), $rest'},
#    {regex = '(?P<text>^.*), (?P<subloc>.*), (?P<loc>.*), (?P<province>.*), (?P<country>Südkorea), (?P<rest>.*$)', replace = '$text, $loc, $province, $country, $rest'},
#    {regex = '(?P<text>^.*), (?P<sublocation>.*), (?P<location>.*), (?P<province>.*), (?P<country>Morocco), (?P<rest>.*$)',replace = '$text, $sublocation, $location, $country, $rest'},
    #zap empty commas from the separator
#    {regex = '^, ', replace = ','},
    #{regex = '\W,+', replace = ''},
    {regex = 'Zurich', replace = 'Zürich'},
    {regex = ' Township', replace = ''},
    {regex = ' Province', replace = ''},
]

# status line metadata (in this order) as provided by the exiv2 library
[[status_line]]
    exif_tags = ["Iptc.Application2.ObjectName"]

[[status_line]]
    exif_tags = ["Iptc.Application2.SubLocation"]

[[status_line]]
    exif_tags = ["Iptc.Application2.City"]
    replace =[{regex= ' City', replace = ''}, {regex = '-si', replace = ''}]

[[status_line]]
    exif_tags = ["Iptc.Application2.ProvinceState"]
    replace = [{regex = '(?i)Mecklenburg-Western\sPomerania', replace = 'MV' },
        {regex = 'Brandenburg', replace = 'Mark'},
        {regex = '-do', replace = ''},
        {regex= '(?i)West Pomeranian Voivodeship', replace = ''}]

[[status_line]]
    exif_tags = ["Iptc.Application2.CountryName"]
    replace = [{regex = 'South\sKorea', replace = 'Südkorea' },
        {regex = '(?i)United\sStates\sOf\sAmerica', replace = 'USA' },
        {regex = 'Germany', replace = ''},
        {regex = 'Morocco', replace = 'Marokko'}]

[[status_line]]
    exif_tags = ["Exif.Photo.DateTimeOriginal"]

# convert date to German format
[[status_line.replace]]
    regex = '(?P<y>\d{4})[-:]0*(?P<M>\d+)[-:]0*(?P<d>\d+)\s+0*(?P<h>\d+:)0*(?P<m>\d+):(?P<s>\d{2})'
    # e.g. with time:  replace = '$d.$M.$y, $h$m'
    replace = '$d.$M.$y'

[[status_line]]
    exif_tags = ["Xmp.dc.creator"]
    # convert input from UPPER CASE to Title Case (there's also the more powerful case_conversion instruction)
    #capitalize = true

    # convert input from case to case (see https://github.com/rutrum/convert-case#cases)
    case_conversion = {from = 'Upper', to = 'Title'}

    # remove everything after the first word, add s/th before name
    replace = [{ regex = '\s.*$', replace = '' }, { regex = '(?P<a>^.*$)', replace = 'von $a' }]


