# Configuration for Rahmen

# these will be overridden if also given on the command line
# Font size of the status line
font_size = 32
# Delay between transitions
delay = 90

# status line metadata (in this order) as provided by the exiv2 library
[[status_line]]
exif_tags = ["Iptc.Application2.ObjectName"]

[[status_line]]
exif_tags = ["Iptc.Application2.SubLocation"]

[[status_line]]
exif_tags = ["Iptc.Application2.City"]
replace = [{regex = 'Land', replace = 'Ld.'}]
[[status_line]]
exif_tags = ["Iptc.Application2.ProvinceState"]
replace = [{ regex = '(?i)Mecklenburg-Western\sPomerania', replace = 'MV' }, {regex = 'Brandenburg', replace = 'Mark Bbg.'}]

[[status_line]]
exif_tags = ["Iptc.Application2.CountryName"]
replace = [{ regex = 'South\sKorea', replace = 'Südkorea' }, { regex = '(?i)United\sStates\sOf\sAmerica', replace = 'USA' }, { regex = 'Germany', replace = ''}]

[[status_line]]
exif_tags = ["Exif.Photo.DateTimeOriginal"]
# convert date to German format
[[status_line.replace]]
regex = '(?P<y>\d{4})[-:]0*(?P<M>\d+)[-:]0*(?P<d>\d+)\s+0*(?P<h>\d+:)0*(?P<m>\d+):(?P<s>\d{2})'
# replace = '$d.$M.$y, $h$m'
replace = '$d.$M.$y'


[[status_line]]
exif_tags = ["Xmp.dc.creator"]
# convert input from UPPER CASE to Title Case
#capitalize = true
## remove numeric strings starting with plus sign after whitespace (phone numbers) and www adresses and everything after the first word, add s/th before name
## replace = [ {regex = '(\s\+\d+)|(\b<?www.)|(\s.*$)', replace = ''}, {regex = '(?P<a>^.*$)', replace = 'von $a'} ]
# remove everything after the first word, add s/th before name
replace = [{ regex = '\s.*$', replace = '' }, { regex = '(?P<a>^.*$)', replace = 'von $a' }]
#case_from = 'Upper'
#case_to = 'Title'
#test error
case_from = 'Trööt'
case_to = 'Trööt'