# Configuration for Rahmen

# these will be overridden if also given on the command line
# Font size of the status line
font_size = 32
# Delay between transitions
delay = 90

# Parameters to tune the information line below the image.
# The following are probably only useful when post-processing using the python snippet
# or the line_replace regex(es).

# What to insert between the metadata, default: insert ", ".
    # separator = "|"

# use this Python script for postprocessing
py_postprocess =  "postprocess"
# look for it in this path
py_path = ["."]

# status line metadata (in this order) as provided by the exiv2 library
[[status_line]]
    exif_tags = ["Iptc.Application2.ObjectName"]

[[status_line]]
    exif_tags = ["Iptc.Application2.SubLocation"]

[[status_line]]
    exif_tags = ["Iptc.Application2.City"]
    replace =[{regex= ' City', replace = ''}, {regex = '-si', replace = ''},{regex= '(-gu)n*', replace = ''}]

[[status_line]]
    exif_tags = ["Iptc.Application2.ProvinceState"]
    replace = [{regex = '(?i)Mecklenburg-Western\sPomerania', replace = 'MV' },
        {regex = 'Brandenburg', replace = 'Mark'},
        {regex = '-do', replace = ''},
        {regex= '(?i)West Pomeranian Voivodeship', replace = ''}]

[[status_line]]
    exif_tags = ["Iptc.Application2.CountryName"]
    replace = [{regex = 'South\sKorea', replace = 'Südkorea' },
        {regex = '(?i)United\sStates\sOf\sAmerica', replace = 'USA' },
        {regex = 'Germany', replace = ''},
        {regex = 'Morocco', replace = 'Marokko'}]

[[status_line]]
    exif_tags = ["Exif.Photo.DateTimeOriginal"]

# convert date to German format
[[status_line.replace]]
    regex = '(?P<y>\d{4})[-:]0*(?P<M>\d+)[-:]0*(?P<d>\d+)\s+0*(?P<h>\d+:)0*(?P<m>\d+):(?P<s>\d{2})'
    # e.g. with time:  replace = '$d.$M.$y, $h$m'
    replace = '$d.$M.$y'

[[status_line]]
    exif_tags = ["Xmp.dc.creator"]
    # convert input from UPPER CASE to Title Case (there's also the more powerful case_conversion instruction)
    #capitalize = true

    # convert input from case to case (see https://github.com/rutrum/convert-case#cases)
    case_conversion = {from = 'Upper', to = 'Title'}

    # remove everything after the first word, add s/th before name
    replace = [{ regex = '\s.*$', replace = '' }, { regex = '(?P<a>^.*$)', replace = 'von $a' }]


