[workspace]
# disable the changelog for all packages
changelog_update = false

[[package]]
name = "rahmen"
# enable the changelog for this package
changelog_update = true
# set the path of the changelog to the root of the repository
changelog_path = "./CHANGELOG.md"
version_group = "rahmen"

# We want all packages to track the same version.
[[package]]
name = "rahmen-exiv2"
version_group = "rahmen"
