name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v2
      id: cache-id
      with:
        path: ${{ runner.temp }}/cache-directory-rahmen
        key: ${{ runner.os }}-cache-rahmen-key-v1.0
    - uses: airvzxf/cache-anything-new-action@v1.0.1
      with:
        script: 'install.sh'
        is_cached: ${{ steps.cache-id.outputs.cache-hit }}
        cache: ${{ runner.temp }}/cache-directory-rahmen
        snapshot: '/'
        exclude: '/boot /data /dev /mnt /proc /run /sys'
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
